.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LDAP2DNS 1 "May 22, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ldap2dns \- LDAP based DNS management system
.SH SYNOPSIS
.B ldap2dns[d]
.RI [ "-D binddn" "] [" "-b searchbase" "] [" "-o data|db" "] [" "-h host" "] [" "-p port" "] [" "-w password" "] [" "-L[filename]" "] [" "-u numsecs" "] [" "-v[v]" "] [" "-V" ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ldap2dns
commands.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page yet.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBldap2dns\fP
is an efficient, administration friendly way to maintain DNS
information and distribute DNS records to multiple primary DNS servers
running
.B djbdns
or
.B BIND
.

.SH OPTIONS
A summary of commanline options is included below.
.TP
.B \-D binddn
Use the distinguished name binddn to bind to the LDAP directory.
.TP
.B \-w bindpasswd
Use bindpasswd as the password for simple authentication.
.TP
.B \-b
Use searchbase as the starting point for the search instead of the default.
.TP
.B \-o data
Generate a "data" file to be processed by
.B tinydns-data
.TP
.B \-o db
For each zone generate a "<zonename>.db" file to be used by
.B named
.TP
.B \-L[filename]
Print output in LDIF format for reimport.
.TP
.B \-h host
Hostname of LDAP server, defaults to localhost.
.TP
.B \-p port
Portnumber to connect to LDAP server, defaults to 389
.TP
.B \-u numsecs
Update DNS data after numsecs. Defaults to 59 if started as daemon.

.br
Important notice: data.cdb is rewritten only after DNSserial in DNSzone is
increased.

.TP
.B \ -e "exec-cmd"
This command is executed after ldap2dns regenerated its data files.

.TP
.B \ -v
Run in verbose mode.

.TP
.B \ -vv
Run in even more verbose mode.

.TP
.B \ -V
Print version and exit.

.SH ENVIRONMENT

.B LDAP2DNS_UPDATE
The LDAP2DNS_UPDATE environment variable sets the time interval in seconds
to update DNS data. This variable is overridden by -u option.

.B LDAP2DNS_OUTPUT
Specify the type of output. It may be set to 'data' so that its output may
be used by tinydns. It may be set to 'db' so that its output may be used
by 'named'. This variable is overridden by the -o option.

.B TINYDNSDIR
The root-directory used by tinydns, ie. the one in which to tinydns expects
its 'data'-file.

.SH FILES

/etc/openldap/ldap.conf
.br
Options specified here fulfil the same purpose as for other ldap-tools.

.SH SEE ALSO

ldap.conf(5), ldapsearch(1), tinydns, named.conf(5).

Please visit the project homepage for more detail:
.RI [ http://ldap2dns.tiscover.com/ ]
.br
.SH AUTHOR
This manual page was written by Johann Botha <joe@blio.net>,
for the Debian GNU/Linux system and is distributed under the GPL version 2
or later.

Jacob Rief <jacob.rief@tiscover.com> is the original author of this program.
